import { createAction } from "redux-actions";
export const LATESTNEWS = {
    GETALL: "LATESTNEWS_GETALL",
    GETALL_SUCCESS: "LATESTNEWS_GETALL_SUCCESS",
    GETALL_FAILURE: "LATESTNEWS_GETALL_FAILURE",
    GETBYID: "LATESTNEWS_GETBYID",
    GETBYID_SUCCESS: "LATESTNEWS_GETBYID_SUCCESS",
    GETBYID_FAILURE: "LATESTNEWS_GETBYID_FAILURE",
    CHANGE_STATUS: "LATESTNEWS_CHANGE_STATUS",
    CHANGE_STATUS_SUCCESS: "LATESTNEWS_CHANGE_STATUS_SUCCESS",
    CHANGE_STATUS_FAILURE: "LATESTNEWS_CHANGE_STATUS_FAILURE",
    DELETE: "LATESTNEWS_DELETE",
    DELETE_SUCCESS: "LATESTNEWS_DELETE_SUCCESS",
    DELETE_FAILURE: "LATESTNEWS_DELETE_FAILURE",
    ADD: "LATESTNEWS_ADD",
    ADD_SUCCESS: "LATESTNEWS_ADD_SUCCESS",
    ADD_FAILURE: "LATESTNEWS_ADD_FAILURE",
    EDIT: "LATESTNEWS_EDIT",
    EDIT_SUCCESS: "LATESTNEWS_EDIT_SUCCESS",
    EDIT_FAILURE: "LATESTNEWS_EDIT_FAILURE",
};
export const getAllLatestNewsAction = createAction(LATESTNEWS.GETALL);
export const getAllLatestNewsSuccessAction = createAction(LATESTNEWS.GETALL_SUCCESS);
export const getAllLatestNewsFailureAction = createAction(LATESTNEWS.GETALL_FAILURE);

export const getByIdLatestNewsAction = createAction(LATESTNEWS.GETBYID);
export const getByIdLatestNewsSuccessAction = createAction(LATESTNEWS.GETBYID_SUCCESS);
export const getByIdLatestNewsFailureAction = createAction(LATESTNEWS.GETBYID_FAILURE);